### ISSUE TITLE
Bind to both ipv4 and ipv6

### ISSUE THREAD

**Issue by diwu1989** [swiftstack/docker-swift#44]
I would like the ability to operate swift docker container using Ipv6.
It looks like the swift proxy right now only listens on ipv4, can we make it to listen to both?

**Comment by diwu1989** [comment]
If I set the `bind_ip` in the proxy-server.conf file to `::`, it will bind to both ipv4 and ipv6 it seems.

**Comment by timuralp** [comment]
@diwu1989 yep, that sounds good. Thank you for the PR! Will merge it shortly.

**Comment by timuralp** [comment]
Resolved via #45
